apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: k8s-python-api-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k8s-python-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80  # For CPU usage over 80%, creating more replicas
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80  # For memory usage over 80%, creating more replicas
