apiVersion: v1
kind: Service
metadata:
  name: k8s-python-app-service
spec:
  selector:
    app: k8s-python-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
